### ISSUE TITLE
failing build, but Travis badge is green

### ISSUE THREAD

**Issue by yangmillstheory** [tableau-mkt/generator-web-data-connector#47]
Hi,

I noticed on my Travis dashboard that the latest build is failing: https://travis-ci.org/tableau-mkt/generator-web-data-connector

From the tests, they look like valid failures. However the badge in the README is green. Is this a Travis bug or our bug?

**Comment by iamEAP** [comment]
Hey @yangmillstheory! That's a legitimate bug, but only exists in a feature branch, not in any released version.

Resolution of that bug would allow us to merge in and release #46

**Comment by yangmillstheory** [comment]
Thanks Eric! I see now that there's no branch restriction in your travis.yml.

**Comment by yangmillstheory** [comment]
@iamEAP does Travis only build against your PR, and not build every time you push to your feature branch?

**Comment by iamEAP** [comment]
I believe it builds on both: with each push, regardless of branch, also separately for each open PR. If a new commit is pushed to a branch that has an associated PR, a new PR build is also triggered.
