### ISSUE TITLE
Error: Bootstrap tooltips require Tether

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt/generator-web-data-connector#48]
Some recent changes to the Bootstrap v4 alpha require tether.  Because of the way we're requiring Bootstrap (the full stack, not just picking individual parts), the following error gets thrown in the Tableau WDC connection window.

```error
Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/) file: http://localhost:9001/build/all.min.js line: 5
```

Strangely, this is never thrown if you're in Tableau or the simulator.  Loading the WDC alone through a web browser does not trigger the error.

**Comment by iamEAP** [comment]
Work on this upstream in twbs/bootstrap#17325.

**Comment by cmtoomey** [comment]
Any way to remove the Tether dependency to avoid this?

**Comment by iamEAP** [comment]
My fault for going with v4 of bootstrap long before it's ready.  It's going to be much simpler to just require tether (rather than going through the process to custom build bootstrap).  Fix incoming.
