### ISSUE TITLE
Modifying main.js script to execute POST request and then GET requests

### ISSUE THREAD

**Issue by ianSHero** [tableau-mkt/generator-web-data-connector#49]
Am trying to access data from facebook api but the api gives an unknown error code when i ask for too much data. Found a way around this by first sending a POST request and then making two other GET requests.

Essentially what is being done here. http://stackoverflow.com/questions/33678489/marketing-api-export-async-report-ads-insights-v2-5

Trying to modify the script to do this but not sure how to go about it. Would appreciate some help. Thanks.

**Comment by iamEAP** [comment]
Hey @ianSHero, I think I understand what you're trying to accomplish, but a snippet of code would be helpful if you could provide it.

**Comment by ianSHero** [comment]
I believe this part of the code does the get request.

$.ajax({
      url: buildApiFrom(requestURI, lastRecord),
      success: function dataRetrieved(response) {
        var processedData = [],
            cursor;

        // If paging.next exists then there is more data, capture the after field
        if (response.paging.next === undefined) {
          moreData = false;
        } else {
          moreData = true;
          cursor = response.paging.cursors.after;
        }


        // You may need to perform processing to shape the data into an array of
        // objects where each object is a map of column names to values.
        response.data.forEach(function shapeData(record) {
          if (record.actions != undefined){  // if there is an action on the record
            for (i=0; i<record.actions.length; i++){
              record[record.actions[i].action_type] = record.actions[i].value;
            }  // Push actions onto record
            delete record.actions;  // Remove old actions object
          }
          processedData.push(record);
        });
        console.log("Table data processed", processedData);

**Comment by ianSHero** [comment]
Hey Eric,

Thanks for the response. I believe it is this part of the script that makes
the GET request right now.

$.ajax({
      url: buildApiFrom(requestURI, lastRecord),
      success: function dataRetrieved(response) {
        var processedData = [],
            cursor;
        // If paging.next exists then there is more data, capture the after
field
        if (response.paging.next === undefined) {
          moreData = false;
        } else {
          moreData = true;
          cursor = response.paging.cursors.after;
        }

        // You may need to perform processing to shape the data into an
array of
        // objects where each object is a map of column names to values.

        response.data.forEach(function shapeData(record) {
          if (record.actions != undefined){  // if there is an action on
the record
            for (i=0; i<record.actions.length; i++){
              record[record.actions[i].action_type] =
record.actions[i].value;
            }  // Push actions onto record
            delete record.actions;  // Remove old actions object
          }
          processedData.push(record);
        });
        console.log("Table data processed", processedData);

        // Once you've retrieved your data and shaped it into the form
expected,
        // call the registerData function. If more data can be retrieved,
then
        // supply a token to inform further paged requests.
        // @see buildApiFrom()

        if (moreData) {
          registerData(processedData, cursor);
        }
        // Otherwise, just register the response data with the callback.
        else {
          registerData(processedData);
        }

      },

      // Use this.ajaxErrorHandler for basic error handling.
      error: this.ajaxErrorHandler

    });

  };

**Comment by ianSHero** [comment]
Hey Eric,

Heres a quick update. So i have figured out how to do the POST request
with:

$.ajax({
      type: 'POST',
      url: buildApiFrom(requestURI),
      success: function(response){
        console.log('success', response);
      }
    });

The problem now is making a GET request using the response above.

Would greatly appreciate any adivce!!

Thanks

**Comment by iamEAP** [comment]
Hey @ianSHero...  Not sure if you're still working on this.  Is there a reason you can just nest a GET request in that success callback?

```javascript
$.ajax({
  type: 'POST',
  url: buildApiFrom(requestURI),
  success: function(postResponse) {
    $.ajax({
      type: 'GET',
      url: buildApiFrom(postResponse.someProperty),
      success: function (getResponse) {
        console.log(getResponse);
      }
    });
  }
});
```

**Comment by iamEAP** [comment]
Closing, as I'm cleaning out the issue queue.
