### ISSUE TITLE
Integrating other node modules

### ISSUE THREAD

**Issue by johandebeurs** [tableau-mkt/generator-web-data-connector#50]
When I use `require('<node module>')` within my main.js file, I get the following error in the Tableau simulator: 
ReferenceError: Can't find variable: require file: http://localhost:9001/build/all.js line: xxxx.  
I've installed the module into /node_modules using `npm install <node module>`, it is included as a project dependency in package.json, but I have hit a wall figuring out what to do next.  Do you have any tips?

**Comment by iamEAP** [comment]
Apologies for the delay @johandebeurs!  Looks like you're trying to use node modules (server-side) in the client-side JavaScript contained in `main.js`.

This isn't really possible _out of the box_, but it's totally possible if you're willing to get your hands a little dirty and do some digging on your own.  You should have a look at [Browserify](http://browserify.org/).  You'll have to modify the way the WDC gets built to use browserify.

Hope that help!
